remote_theme: mmistakes/minimal-mistakes

# Site Settings
locale: "en-US"
title: "Chendong Xin"
title_separator: "-"
subtitle: "Robotics Undergrad Researcher"
name: "Chendong Xin"
description: >-
  An undergraduate researcher in Robotics from Tsinghua University, focused on robotic manipulation.
url: "https://star-xcd.github.io"
baseurl: ""
repository: "Star-Xcd/star-xcd.github.io"

# Site Configuration
timezone: Asia/Shanghai
minimal_mistakes_skin: mint
search: true
breadcrumbs: false
words_per_minute: 200

# Site Author
author:
  name: "Chendong Xin"
  avatar: "assets/images/bio-photo.jpg"
  bio: "An undergraduate researcher in Robotics from Tsinghua University, focused on robotic manipulation."
  location: "Tsinghua University, China"
  email: "xcd22@mails.tsinghua.edu.cn"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Star-Xcd"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/slovartephese"

# Site Footer
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:xcd22@mails.tsinghua.edu.cn"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Star-Xcd"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/slovartephese"

# Reading Files
include:
  - .htaccess
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  # - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # # _posts
  # - scope:
  #     path: ""
  #     type: posts
  #   values:
  #     layout: single
  #     author_profile: true
  #     read_time: true
  #     comments: false
  #     share: true
  #     related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# SEO settings
seo:
  type: "Person"
  name: "Chendong Xin"
  links:
    - "https://github.com/Star-Xcd"
    - "https://star-xcd.github.io"
